// Generated from content/dares.json by tooling/dares/catalog.py.
// Edit the reviewed source, regenerate, then run dart format.
const curatedDares = <String, List<String>>{
  "happy": [
    "Take a photo of one small thing that made you smile today.",
    "Do a little happy dance, seated or standing. Record 10 seconds at your own pace.",
    "Say one happy memory in a 15-second video. Keep other people's names private.",
    "Draw a smiling face on paper. Take a photo of your drawing.",
    "Arrange three things in a color you love. Take a photo of them together.",
    "Find a bright spot in your room. Take a photo of the light, not the sun.",
    "Make up a short tune and hum it in a 10-second video.",
    "Write one kind thing about yourself. Show only that line in a photo.",
    "Find an object that reminds you of a good day. Take a photo of it.",
    "Make a small paper flag for something you finished today. Show your flag.",
    "Send a kind message to a friend. Keep it private, then show a thumbs-up in a photo.",
    "Give a favorite object a happy name. Introduce it in a 15-second video.",
  ],
  "relaxed": [
    "Sit comfortably and take five gentle breaths without forcing them. Stop if uncomfortable. Afterward, photograph a quiet object nearby.",
    "Rest your hands comfortably and let your shoulders ease down. Afterward, take a photo of your resting spot.",
    "Notice three colors around you. Take a photo of the color you like most.",
    "Hold a soft cloth and notice how it feels. Take a photo of its folds.",
    "Make a small, clear space beside you. Photograph that space when you are done.",
    "Listen to a gentle song off-camera. Afterward, draw one line that fits its sound and photograph it.",
    "Look at a plant from a comfortable spot. Take a photo of one detail you notice.",
    "Draw slow loops on paper at your own pace. Show the page when you are ready.",
    "Place a favorite object within reach. Take a photo of your simple rest corner.",
    "Notice the support of your chair or bed. Afterward, take a photo of a nearby cushion or blanket.",
    "Read a few lines of a book off-camera. Then show the closed book in a photo.",
    "Write 'I can take a break' on a blank page. Take a photo of that line.",
  ],
  "calm": [
    "Look around and name three things you can see. Then photograph one safe, ordinary object.",
    "Notice two sounds around you with your eyes open. Describe one in a 10-second video.",
    "Trace the edge of a piece of paper slowly with your finger. Record up to 15 seconds.",
    "Find a still object near you. Take a close photo of its shape.",
    "Draw three slow lines without trying to make them perfect. Photograph your page.",
    "Put three small, safe objects in a row. Take a photo of your row.",
    "Turn off one sound you control for a short break. Afterward, show a quiet corner in a photo.",
    "Look for a soft color in your room. Take a photo of it.",
    "Rest your hands on a comfortable surface. Take a photo of the surface's pattern.",
    "Look out from a safe indoor spot. Photograph a cloud or tree without showing your address.",
    "Write one small thing you can do next on blank paper. Show just that step.",
    "Take a moment to notice the room around you. Record a slow 10-second view with no people or private details.",
  ],
  "energetic": [
    "Sit up at your own pace and tap a gentle beat with your hands. Record 10 seconds.",
    "Choose a song you enjoy. Move your hands to its beat for a 15-second video.",
    "March gently in place or tap your hands while seated. Record 10 seconds. Stop if uncomfortable.",
    "Open a curtain if it is safe and comfortable. Photograph the light on a nearby wall.",
    "Put away three things near you. Take a photo of the clear space afterward.",
    "Make up a small wake-up move you can do seated. Show it in a 10-second video.",
    "Write one small plan for this morning on blank paper. Photograph just that plan.",
    "Pick an item of clothing that feels good to wear. Show its color in a photo.",
    "Gently open and close your hands a few times. Record up to 10 seconds without pushing through pain.",
    "Take a short walk or move comfortably around your room off-camera. Stop, then take a photo of a color you found.",
    "Set out one thing you need for your next task. Take a photo with private details hidden.",
    "Invent a short cheer for starting your day. Say it in a 10-second video.",
  ],
  "sad": [
    "Pick an object that feels comforting to you. Take a photo of it. You do not need to smile.",
    "Draw a color or shape for how today feels. Take a photo of the drawing without explaining anything private.",
    "Send a private hello to someone you trust, if you want company. Afterward, photograph a nearby object, not the message.",
    "Wrap up in a comfortable blanket if you like. Take a photo of its color or pattern.",
    "Do one small, kind thing for yourself off-camera. Then show an object connected to it.",
    "Write 'One small step is enough' on blank paper. Take a photo of that line.",
    "Notice one detail in a plant, the sky, or a picture of nature. Photograph that detail from a safe spot.",
    "Move one item to make your resting space more comfortable. Photograph the result.",
    "Listen to a comforting song off-camera. Then draw a shape that fits it and show your drawing.",
    "Choose a simple task that feels manageable, such as putting away one item. Photograph the result.",
    "Draw a small place where you would like to rest. Show your drawing without sharing a real address.",
    "Find a texture you like, such as a smooth cup or soft cloth. Take a close photo of it.",
  ],
  "productive": [
    "Put away three things on one surface. Take a photo of the space you cleared.",
    "Write one small next step on blank paper. Photograph the step, not your private task list.",
    "Choose one pen, tool, or other item for your next task. Take a photo of it ready to use.",
    "Fold one item of clothing. Photograph the finished fold.",
    "Sort a small pile of your own safe objects into two groups. Photograph the result.",
    "Finish a small task off-camera. Record a 10-second celebration without showing private work.",
    "Make a blank-paper checklist with just one easy task. Tick it after doing it and take a photo.",
    "Place something you often need in an easy-to-reach spot. Photograph it without showing keys or private details.",
    "Choose one thing to do tomorrow. Draw a simple symbol for it and photograph your drawing.",
    "Clear a small space for a break. Take a photo of the space when you are done.",
    "Close an app you do not need right now. Then photograph one real-world object you want to focus on.",
    "Write a kind reminder to start small. Put it near your work area and photograph only the note.",
  ],
  "grateful": [
    "Find an everyday object that helps you. Take a photo of it and say why in a short video if you like.",
    "Write one small thing you appreciate on blank paper. Photograph just that line.",
    "Thank someone privately for a specific kindness. Then photograph a hand-drawn heart, not your conversation.",
    "Notice a useful part of your room that you often overlook. Take a photo of it.",
    "Draw a simple symbol for a person who has helped you. Photograph it without names or faces.",
    "Find something you have used for a long time. Show it in a photo.",
    "Think of a skill you have learned. Show one small part of it in a 15-second video.",
    "Notice a pleasant sound nearby. Describe it in a 10-second video without recording other people's conversations.",
    "Take a photo of a small detail in nature that you appreciate. Stay in a safe place.",
    "Write a thank-you note to your past self for one small effort. Photograph a line you are comfortable sharing.",
    "Choose an object linked to a kind memory. Photograph it without sharing anyone else's private story.",
    "Do a small helpful task in your own space. Photograph the finished result, without showing other people.",
  ],
  "creative": [
    "Draw your favorite animal using only five lines. Take a photo of your drawing.",
    "Build a small shape with three safe objects from your desk. Photograph it on a stable surface.",
    "Take a photo of an ordinary object from a new angle.",
    "Draw your mood using one color. Photograph the page when you are ready.",
    "Write a two-line poem about today's weather. Read it in a 15-second video.",
    "Make a face from three pieces of paper. Take a photo of your paper face.",
    "Invent a new name for a color you can see. Show the color in a 10-second video and say its name.",
    "Find two objects with different textures. Photograph them side by side.",
    "Draw a tiny home for an imaginary animal. Take a photo of your design.",
    "Make a simple beat by tapping your hands gently. Record 10 seconds.",
    "Fold a sheet of paper into any shape you like. Take a photo of what you made.",
    "Arrange three objects to tell a tiny story. Explain it in a 20-second video.",
  ],
  "curious": [
    "Find a detail on an everyday object you have not noticed before. Take a close photo of it.",
    "Look up one fact about an animal using a trusted source. Share it in a 20-second video and name the source.",
    "Find two things with the same shape but different uses. Photograph them together.",
    "Choose a safe object and guess what it is made from. Check its label off-camera, then share what you learned in a 15-second video.",
    "Learn a new word off-camera. Say the word and its simple meaning in a 15-second video.",
    "Look for a pattern in a leaf or a picture of one. Take a photo of the pattern.",
    "Find a shadow made by an everyday object. Photograph the shadow and let people guess the object.",
    "Ask a willing friend a simple question off-camera. Share only your own question in a short video, not their answer.",
    "Look closely at a piece of cloth. Take a photo of one detail you find.",
    "Find an object with moving parts that is safe to handle. Show how one part works in 15 seconds.",
    "Learn how to fold a simple paper shape off-camera. Photograph your first try, even if it is uneven.",
    "Choose one thing you would like to learn. Draw a symbol for it and show your drawing.",
  ],
  "bored": [
    "Find three things of the same color near you. Arrange them for a photo.",
    "Give a harmless object a made-up story. Tell it in a 20-second video.",
    "Draw a tiny maze on blank paper. Take a photo of your maze.",
    "Make a small tower from three soft or unbreakable objects on a stable surface. Photograph it.",
    "Find a new camera angle for your favorite mug. Take a photo without climbing on anything.",
    "Draw an animal using circles only. Show your drawing in a photo.",
    "Invent a name for an imaginary shop. Make a paper sign and photograph it.",
    "Choose a letter and find two nearby objects whose names start with it. Photograph them together.",
    "Fold a piece of paper into a small fan. Show it in a 10-second video.",
    "Create a simple hand beat. Repeat it in a 10-second video.",
    "Arrange safe objects from smallest to largest. Take a photo of your row.",
    "Pretend an everyday object is a prize. Present it in a 15-second video.",
  ],
  "silly": [
    "Introduce a spoon as if it is a movie star. Record a 15-second video.",
    "Make up a five-second celebration move, seated or standing. Record it at your own pace.",
    "Draw your face with the hand you use less. Photograph the result.",
    "Give a pillow a funny job title. Introduce it in a 10-second video.",
    "Say a simple sentence in your own made-up robot voice. Keep the video under 15 seconds.",
    "Balance a folded cloth on your head while seated, if comfortable. Take a photo; skip it if it slips.",
    "Draw a fruit wearing a tiny hat. Show your drawing in a photo.",
    "Pretend to give a weather report for your room. Record 15 seconds without showing private details.",
    "Make your funniest comfortable face for a photo. Do not pull on your skin.",
    "Give two safe objects a made-up conversation. Record up to 20 seconds.",
    "Turn a blank piece of paper into a pretend award. Photograph your award.",
    "Invent a silly greeting using only your hands. Show it in a 10-second video.",
  ],
  "goofy": [
    "Pretend a sock is a friendly puppet. Give it a name in a 10-second video.",
    "Draw a cat with very long ears. Take a photo of your drawing.",
    "Act surprised by an ordinary cup. Record your reaction in a five-second video.",
    "Make up a harmless sound for a toy or object. Show it in a 10-second video.",
    "Put two soft toys in a pretend meeting. Photograph the scene.",
    "Pretend to interview a cushion. Ask one funny question in a 15-second video.",
    "Draw a tiny face on blank paper and place it beside a plant. Take a photo without harming the plant.",
    "Make an imaginary snack out of paper shapes. Photograph it; do not eat the paper.",
    "Show a tiny seated dance using only your fingers. Record 10 seconds.",
    "Pretend your pen is reporting live from your desk. Record a 15-second video.",
    "Draw a fish with shoes. Show your drawing in a photo.",
    "Invent a funny name for your blanket. Announce it in a 10-second video.",
  ],
  "christmas": [
    "Take a photo of a decoration you enjoy, with no people or private details in view.",
    "Make a small paper star. Photograph it on a safe surface.",
    "Write a kind holiday wish on blank paper. Take a photo without adding anyone's name.",
    "Arrange three objects in festive colors. Take a photo of them together.",
    "Draw a holiday scene you would enjoy. Photograph your drawing.",
    "Fold a napkin into any festive shape. Take a photo of your first try.",
    "Make a gift tag from spare paper. Photograph it before adding personal details.",
    "Draw a winter hat on a paper character. Show your drawing.",
    "Share one small holiday tradition in a 20-second video. Keep family details private.",
    "Place a soft toy beside a paper decoration. Photograph your little scene.",
    "Help with one small task at home off-camera. Then photograph a decoration you like.",
    "Make up a friendly holiday greeting. Say it in a 10-second video.",
  ],
  "new year": [
    "Write one small thing you would like to try this year. Photograph that line on blank paper.",
    "Draw a symbol for a fresh start. Take a photo of your drawing.",
    "Choose an object that reminds you of something you learned. Show it in a 15-second video.",
    "Make a paper sign with one kind word for your new year. Photograph it.",
    "Clear one small space for something you enjoy. Take a photo of the result.",
    "Write a friendly note to your future self. Photograph only a line you want to share.",
    "Invent a gentle celebration move you can do seated. Record 10 seconds.",
    "Pick a color for your year and find an object in that color. Take a photo.",
    "Name one small habit you would like to keep in a 15-second video. Avoid private details.",
    "Draw a tiny picture of a memory you enjoy. Photograph the drawing without names or dates.",
    "Make a paper badge for an effort you made last year. Take a photo of it.",
    "Choose one easy first step toward something you care about. Show a safe object linked to that step.",
  ],
  "chill": [
    "Sit comfortably and take five gentle breaths without forcing them. Stop if uncomfortable. Afterward, photograph a quiet object nearby.",
    "Rest your hands comfortably and let your shoulders ease down. Afterward, take a photo of your resting spot.",
    "Notice three colors around you. Take a photo of the color you like most.",
    "Hold a soft cloth and notice how it feels. Take a photo of its folds.",
    "Make a small, clear space beside you. Photograph that space when you are done.",
    "Listen to a gentle song off-camera. Afterward, draw one line that fits its sound and photograph it.",
    "Look at a plant from a comfortable spot. Take a photo of one detail you notice.",
    "Draw slow loops on paper at your own pace. Show the page when you are ready.",
    "Place a favorite object within reach. Take a photo of your simple rest corner.",
    "Notice the support of your chair or bed. Afterward, take a photo of a nearby cushion or blanket.",
    "Read a few lines of a book off-camera. Then show the closed book in a photo.",
    "Write 'I can take a break' on a blank page. Take a photo of that line.",
  ],
  "energized": [
    "Sit up at your own pace and tap a gentle beat with your hands. Record 10 seconds.",
    "Choose a song you enjoy. Move your hands to its beat for a 15-second video.",
    "March gently in place or tap your hands while seated. Record 10 seconds. Stop if uncomfortable.",
    "Open a curtain if it is safe and comfortable. Photograph the light on a nearby wall.",
    "Put away three things near you. Take a photo of the clear space afterward.",
    "Make up a small wake-up move you can do seated. Show it in a 10-second video.",
    "Write one small plan for this morning on blank paper. Photograph just that plan.",
    "Pick an item of clothing that feels good to wear. Show its color in a photo.",
    "Gently open and close your hands a few times. Record up to 10 seconds without pushing through pain.",
    "Take a short walk or move comfortably around your room off-camera. Stop, then take a photo of a color you found.",
    "Set out one thing you need for your next task. Take a photo with private details hidden.",
    "Invent a short cheer for starting your day. Say it in a 10-second video.",
  ],
};
